//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace applicationapi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class newtravelbookingsystem : DbContext
    {
        public newtravelbookingsystem()
            : base("name=newtravelbookingsystem")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TravelRequest> TravelRequests { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Usertype> Usertypes { get; set; }
    
        public virtual ObjectResult<employeelist_Result> employeelist()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<employeelist_Result>("employeelist");
        }
    
        public virtual ObjectResult<pendingtable_Result> pendingtable()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pendingtable_Result>("pendingtable");
        }
    
        public virtual int sp_Storeprocuser(Nullable<int> requestid, Nullable<System.DateTime> request_Date, string from_location, string to_Location, Nullable<int> userid, string current_Status, string option)
        {
            var requestidParameter = requestid.HasValue ?
                new ObjectParameter("Requestid", requestid) :
                new ObjectParameter("Requestid", typeof(int));
    
            var request_DateParameter = request_Date.HasValue ?
                new ObjectParameter("Request_Date", request_Date) :
                new ObjectParameter("Request_Date", typeof(System.DateTime));
    
            var from_locationParameter = from_location != null ?
                new ObjectParameter("from_location", from_location) :
                new ObjectParameter("from_location", typeof(string));
    
            var to_LocationParameter = to_Location != null ?
                new ObjectParameter("To_Location", to_Location) :
                new ObjectParameter("To_Location", typeof(string));
    
            var useridParameter = userid.HasValue ?
                new ObjectParameter("Userid", userid) :
                new ObjectParameter("Userid", typeof(int));
    
            var current_StatusParameter = current_Status != null ?
                new ObjectParameter("current_Status", current_Status) :
                new ObjectParameter("current_Status", typeof(string));
    
            var optionParameter = option != null ?
                new ObjectParameter("Option", option) :
                new ObjectParameter("Option", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Storeprocuser", requestidParameter, request_DateParameter, from_locationParameter, to_LocationParameter, useridParameter, current_StatusParameter, optionParameter);
        }
    }
}
