//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace applicationapi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.TravelRequests = new HashSet<TravelRequest>();
        }
    
        public int User_id { get; set; }
        [Required(ErrorMessage ="this field is required",AllowEmptyStrings =false)]
        public string Login_Id { get; set; }
        [Required(ErrorMessage = "this field is required", AllowEmptyStrings = false)]
        public string Password { get; set; }
        [Required(ErrorMessage = "this field is required", AllowEmptyStrings = false)]
        public Nullable<int> User_type_id { get; set; }
        [Required(ErrorMessage = "this field is required", AllowEmptyStrings = false)]
        public string Name { get; set; }
        [Required(ErrorMessage = "this field is required", AllowEmptyStrings = false)]
        public Nullable<int> Manageruserid { get; set; }
        [Required(ErrorMessage = "this field is required", AllowEmptyStrings = false)]

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TravelRequest> TravelRequests { get; set; }
        public virtual Usertype Usertype { get; set; }
    }
}
